<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
    <id>17535</id>
    <title>Untar re-exec error unexpected EOF while pulling image (1.9rc3)</title>
    <description>
        <paragraph id="3">
            <sentence id="3.1">I retried the 'docker run python python -m SimpleHTTPServer' a few times with</sentence>
        </paragraph>
        <paragraph id="5">
            <sentence id="5.1">but I wasn't able to repro this issue so I guess it's might be a race condition or a bug in Docker Hub...</sentence>
        </paragraph>
    </description>
</bug>
