<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
    <id>28308</id>
    <title>Container daemon crashes while trying to process a DNS request</title>
    <description>
        <paragraph id="8">
            <sentence id="8.1">**Description**</sentence>
            <sentence id="8.2">The contained daemon has crashed while one of the containers was handling an HTTP request.</sentence>
            <sentence id="8.3">Here is the [panic log](https://github.com/docker/docker/files/586170/docker.log.gz).</sentence>
        </paragraph>
        <paragraph id="9">
            <sentence id="9.1">**Steps to reproduce the issue:**</sentence>
            <sentence id="9.2">I was not able to reproduce the issue.</sentence>
        </paragraph>
        <paragraph id="10">
            <sentence id="10.1">**Describe the results you received:**</sentence>
            <sentence id="10.2">Container daemon panicked.</sentence>
        </paragraph>
        <paragraph id="11">
            <sentence id="11.1">**Describe the results you expected:**</sentence>
            <sentence id="11.2">I'd expect the container daemon to not to crash.</sentence>
        </paragraph>
        <paragraph id="12">
            <sentence id="12.1">**Additional information you deem important (e.g. issue happens only occasionally):**</sentence>
        </paragraph>
        <paragraph id="13">
            <sentence id="13.1">This was the first time it happened, never experienced this issue before.</sentence>
        </paragraph>
        <paragraph id="19">
            <sentence id="19.1">**Additional environment details (AWS, VirtualBox, physical, etc.):**</sentence>
        </paragraph>
        <paragraph id="20">
            <sentence id="20.1">Standard DigitalOcean installation of Docker.</sentence>
        </paragraph>
    </description>
</bug>
