<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
    <id>HHH-7328</id>
    <title>Binding a self-referencing many-to-one attribute results in NullPointerException</title>
    <description>
        <paragraph id="1">
            <sentence id="1.1">This can be reproduced by executing org.hibernate.test.onetomany.RecursiveBidirectionalOneToManyNoCacheTest with -Dhibernate.test.new_metadata_mappings=true.</sentence>
        </paragraph>
        <paragraph id="2">
            <sentence id="2.1">After this issue is fixed, the test may still fail for other reasons.</sentence>
        </paragraph>
    </description>
</bug>
