<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
    <id>48130</id>
    <title>Breakpoint in renamed project leads to exception</title>
    <description>
        <paragraph id="1">
            <sentence id="1.1">I ran into this originally in a more elaborate plugin development scenario on 2 1.1.</sentence>
            <sentence id="1.2">However I can reproduce it with 3.0 M5 as well.</sentence>
            <sentence id="1.3">Here are the steps:</sentence>
            <sentence id="1.4">1 Create a simple java project with one class and a main method.</sentence>
            <sentence id="1.5">2 Set a breakpoint in the main method.</sentence>
            <sentence id="1.6">3 Create a launch configuration of type application</sentence>
            <sentence id="1.7">4 debug and observe how the breakpoint is hit correctly</sentence>
            <sentence id="1.8">5 refactor the project's name.</sentence>
            <sentence id="1.9">6 Go into the debug debug perspective.</sentence>
            <sentence id="1.10">There will be exceptions in the .log file or ErrorLog window.</sentence>
        </paragraph>
    </description>
</bug>
